from local_settings import PROJECT_ROOT_ADDRESS, OMNIGLOT_RAW_DATA_ADDRESS, IMAGENET_RAW_DATA_ADDRESS, \
MINI_IMAGENET_RAW_DATA_ADDRESS, CELEBA_RAW_DATA_ADDRESS, LFW_RAW_DATA_ADDRESS, VGG_FACE2, ISIC_RAW_DATASET_ADDRESS, \
EUROSAT_RAW_DATASET_ADDRESS, PLANT_DISEASE_DATASET_ADDRESS, CHESTX_RAY8_RAW_DATASET_ADDRESS, CUB_RAW_DATASEST_ADDRESS, \
AIRCRAFT_RAW_DATASET_ADDRESS, DTD_RAW_DATASET_ADDRESS, VGG_FLOWER_RAW_DATASET_ADDRESS, MSCOCO_RAW_DATASET_ADDRESS, \
TRAFFIC_SIGN_RAW_DATASET_ADDRESS, FUNGI_RAW_DATASET_ADDRESS, VOXCELEB_RAW_DATASEST_ADDRESS


try:
    from local_settings import FLUSH_OUTPUT
except:
    FLUSH_OUTPUT = False

try:
    from local_settings import DEBUG
except:
    DEBUG = False